<div class="copyrightdiv">
    <div class="copyrightdiv1 copyrightfloatdiv">
    <img src="<?php echo $this->getViewFileUrl('images/footerlogo.png'); ?>" class="smallimg" />  
    </div>
    <div class="copyrightdiv2 copyrightfloatdiv">
        <h4>Delilah's Cafe & Catering</h4>
        <p>Unit 5,Building 3,Road 15,Block 515,Saar,Kingdom of Bahrain</p>
        <p>Tel:+97317739726</p>
    </div>
    <div class="copyrightdiv3 copyrightfloatdiv">
    <img src="<?php echo $this->getViewFileUrl('images/bmmi.png'); ?>" class="smallimg1" />  
   </div>
   <div class="paragraphdiv copyrightfloatdiv"><p class="paragraphstyle">Visit BMMI website </p></div>
    <div class="copyrightdiv4 copyrightfloatdiv">
        <p>copyright</p>
    </div>
</div>

