<div class="footericons">
<div class="footericons1"><a  href="#" class="linkfooterdiv3a1"><i class="fab fa-facebook-f iconstyle"></i></a></div>
<div class="footericons1"><a  href="#" class="linkfooterdiv3a1"><i class="fab fa-tumblr iconstyle"></i></a></div>
<div class="footericons1"><a  href="#"  class="linkfooterdiv3a1"><i class="fab fa-linkedin-in iconstyle"></i></a></div>
<div class="footericons1 googleicon"><a  href="#"  class="linkfooterdiv3a1"><i class="fab fa-google-plus-g iconstyle"></i></a></div>
</div>