<div class="maincontent">
 <div class="maincontentdiv1"></div>
 <div class="maincontentdiv2">
    <div class="middlepage">
        <h4 class="middlepagehstyle">RECOMMENDED FOR YOU</h4>
        <p>Mauris semper vehicula luctus.Duis faucibus,ipsum vel hendreit ornare,mi </p>
        <p>lorem sodales mi,porta maximus sapien mauris sodales mauris. Nulla facilisi</p>
        <p>provin pulvinar lacus ex,sed commodo libero gravida et.Sed et nulla lobortis</p>
        <p>luctus purus ac,malesuada turpis.Ut et felis ac diam imprediet pulvinar in</p>
        <p>blandit arcu</p>
        <div class="row">
        <?php echo $block->getLayout()->createBlock('Mageplaza\Productslider\Block\FeaturedProducts')->setProductsCount(12)->setTemplate('Mageplaza_Productslider::productslider.phtml')->toHtml();?>
      </div>
    </div>
 <div class="pagebottom">
     <div class="pagebottom1">
        <div class="galleryimg1"><img src="<?php echo $this->getViewFileUrl('images/galleryimg1.png'); ?>" class="" /> </div>
        <div class="galleryimg1"><img src="<?php echo $this->getViewFileUrl('images/galleryimg2.png'); ?>" class="" /> </div>
        <div class="galleryimg1" ><img src="<?php echo $this->getViewFileUrl('images/galleryimg3.png'); ?>" class="" /> </div>
        <div class="galleryimg1"><img src="<?php echo $this->getViewFileUrl('images/galleryimg4.png'); ?>" class="" /> </div>
        <div class="galleryimg1"><img src="<?php echo $this->getViewFileUrl('images/galleryimg5.png'); ?>" class="" /> </div>
        <div class="galleryimg1"><img src="<?php echo $this->getViewFileUrl('images/galleryimg6.png'); ?>" class="" /> </div>
     </div>
     <div class="pagebottom2">
        <div class="galleryimg2"><img src="<?php echo $this->getViewFileUrl('images/galleryimg7.png'); ?>" class="" /> </div>
        <div class="galleryimg2"><img src="<?php echo $this->getViewFileUrl('images/galleryimg8.png'); ?>" class="" /> </div>
        <div class="galleryimg2"><img src="<?php echo $this->getViewFileUrl('images/galleryimg9.png'); ?>" class="" /> </div>
        <div class="galleryimg2"><img src="<?php echo $this->getViewFileUrl('images/galleryimg10.png'); ?>" class="" /> </div>
        <div class="galleryimg2"><img src="<?php echo $this->getViewFileUrl('images/galleryimg11.png'); ?>" class="" /> </div>
        <div class="galleryimg2"><img src="<?php echo $this->getViewFileUrl('images/galleryimg12.png'); ?>" class="" /> </div>
    </div>
    <div class="bottomtext">
        <p class="bottomparagraph">"Macroons are to die for and I got a free extra one in my order.It's the best <span class="botomspan">Macroons in Baharin! Yummy!"</span></p>
        <h4 class="bottomheading">Jassin Mohammed</h4>
    </div>
   
 </div>

</div>
 <div class="bootomicon">
    <div class="arrowimg"><img src="<?php echo $this->getViewFileUrl('images/arrowimg.png'); ?>" class="" /> </div>
    <div class="arrowimg"><p>To the top</p></div>
    </div>
 </div>
 