<div class="sidebar">
<form action="/action_page.php">
<label class="checkboxlabel">CATEGORY</label><br>
 <div class="checkboxoptiondiv"><input type="checkbox" id="category1" name="category1" value="category1">
  <label for="category1" class="checkboxoption">Category 1</label><br>
  <input type="checkbox" id="category2" name="category2" value="category2">
  <label for="category2" class="checkboxoption">Category 2</label><br>
  <input type="checkbox" id="category3" name="category3" value="category3">
  <label for="category3" class="checkboxoption">Category 3</label><br>
  <input type="checkbox" id="category4" name="category4" value="category4">
  <label for="category4" class="checkboxoption">Category 4</label> </div><br><br>

  <label  class="checkboxlabel">LEAD TIME</label><br>
  <div class="checkboxoptiondiv"> 
   <input type="checkbox" id="option1" name="option1" value="option1">
  <label for="option1" class="checkboxoption">Option 1</label><br>
  <input type="checkbox" id="option2" name="option2" value="option2">
  <label for="option2" class="checkboxoption">Option 2</label><br>
  <input type="checkbox" id="option3" name="option3" value="option3">
  <label for="option3" class="checkboxoption">Option 3</label></div><br><br>

  <label  class="checkboxlabel">DIETARY REQUIREMENTS</label><br>
  <div class="checkboxoptiondiv"><input type="checkbox" id="option1" name="option1" value="option1">
  <label for="option1" class="checkboxoption">Option 1</label><br>
  <input type="checkbox" id="option2" name="option2" value="option2">
  <label for="option2" class="checkboxoption">Option 2</label><br>
  <input type="checkbox" id="option3" name="option3" value="option3">
  <label for="option3" class="checkboxoption">Option 3</label></div><br><br>

  <label  class="checkboxlabel">PRICE & RATING</label><br>
  <div class="checkboxoptiondiv"><input type="checkbox" id="option1" name="option1" value="option1">
  <label for="option1" class="checkboxoption">Option 1</label><br>
  <input type="checkbox" id="option2" name="option2" value="option2">
  <label for="option2" class="checkboxoption">Option 2</label><br>
  <input type="checkbox" id="option3" name="option3" value="option3">
  <label for="option3" class="checkboxoption">Option 3</label></div><br><br>

  <label  class="checkboxlabel">OCCASION</label><br>
  <div class="checkboxoptiondiv"><input type="checkbox" id="option1" name="option1" value="option1">
  <label for="option1" class="checkboxoption">Option 1</label><br>
  <input type="checkbox" id="option2" name="option2" value="option2">
  <label for="option2" class="checkboxoption">Option 2</label><br>
  <input type="checkbox" id="option3" name="option3" value="option3">
  <label for="option3" class="checkboxoption">Option 3</label></div><br><br>
  
  <label  class="checkboxlabel">TYPE OF DISH</label><br>
  <div class="checkboxoptiondiv"><input type="checkbox" id="option1" name="option1" value="option1">
  <label for="option1" class="checkboxoption">Option 1</label><br>
  <input type="checkbox" id="option2" name="option2" value="option2">
  <label for="option2" class="checkboxoption">Option 2</label><br>
  <input type="checkbox" id="option3" name="option3" value="option3">
  <label for="option3" class="checkboxoption">Option 3</label></div><br><br>

  <label  class="checkboxlabel">PREPARATION REQUIREMENTS</label><br>
  <div class="checkboxoptiondiv"><input type="checkbox" id="option1" name="option1" value="option1">
  <label for="option1" class="checkboxoption">Option 1</label><br>
  <input type="checkbox" id="option2" name="option2" value="option2">
  <label for="option2" class="checkboxoption">Option 2</label><br>
  <input type="checkbox" id="option3" name="option3" value="option3">
  <label for="option3" class="checkboxoption">Option 3</label></div><br><br>

  <label  class="checkboxlabel">SERVING SIZE</label><br>
  <div class="checkboxoptiondiv"><input type="checkbox" id="option1" name="option1" value="option1">
  <label for="option1" class="checkboxoption">Option 1</label><br>
  <input type="checkbox" id="option2" name="option2" value="option2">
  <label for="option2" class="checkboxoption">Option 2</label><br>
  <input type="checkbox" id="option3" name="option3" value="option3">
  <label for="option3" class="checkboxoption">Option 3</label></div><br><br>
</form>
  <a href="" class="registerref">Register</a>
</div>